[workspace]
members = [
    "ethereum",
    "swap",
    "tari"
]
exclude = ["tari/template"]

[workspace.dependencies]
ethers = { version = "2.0.7", default-features = false }
sha2 = "0.10.7"
thiserror = "1.0.43"
tokio = "1.29.1"