[package]
name = "swap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { workspace = true }
ethereum = { path = "../ethereum" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }